config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :creatures
  resources :tags

end

app/models/creature.rb
class Creature < ActiveRecord::Base
  has_and_belongs_to_many :tags
end

app/models/creatures_tag.rb
class CreaturesTag < ActiveRecord::Base
  belongs_to :creature
  belongs_to :tag
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :creatures

   def destroy
    transaction do
      valid?(:destroy) or raise RecordInvalid.new(self)
      super()
    end
  end

  private

  def does_not_have_any_creatures
    errors.add(:tags, :present) if creatures_tags.exists?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/creatures_controller.rb
class CreaturesController < ApplicationController
  def index
    @creatures = Creature.all
  end

  def new
    @creature = Creature.new
    @tags = Tag.all
  end

  def show
    @creature = Creature.find(params[:id])
    @tags = @creature.tags
  end

  def create
    # render json: params

    c = Creature.create(creature_params)
    update_tags c

    redirect_to creatures_path
  end

  def update
    c = Creature.find params[:id]
    c.update creature_params

    c.tags.clear
    update_tags c

    redirect_to c
  end

  def edit
    @creature = Creature.find params[:id]
    @tags = Tag.all
  end

  def destroy
    Creature.find(params[:id]).delete
    redirect_to creatures_path
  end

  private

  def update_tags creature
    creature_tags = params[:creature][:tag_ids]
    creature_tags.each do |id|
      creature.tags << Tag.find(id) unless id.blank?
    end
  end

  def creature_params
    params.require(:creature).permit(:name, :description)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.all
  end

  def show
    @tag = Tag.find params[:id]
  end

  def new
    @tag = Tag.new
  end

  def create
    #render json:params
    c = Tag.create(tag_params)
    redirect_to tags_path
  end

  # def destroy
  #   tag.find(params[:id]).delete
  #   redirect_to tags_path
  # end


  private
  def tag_params
    params.require(:tag).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/creatures_helper.rb
module CreaturesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/creatures/_form.html.erb
<%= bootstrap_form_for @creature do |c| %>
  <%= c.text_field :name %>
  <%= c.text_area :description %>

  <%= c.collection_check_boxes :tag_ids, @tags, :id, :name %>

  <%= c.primary %>
<% end %>

app/views/creatures/edit.html.erb
<%= link_to "&larr; Back".html_safe, creatures_path, class: "btn btn-primary" %>

<h2>Edit a Creature</h2>

<%= render 'creatures/form' %>

app/views/creatures/index.html.erb
<h2>Creature List</h2>

<%= link_to "&larr; Back".html_safe, root_path, class: "btn btn-primary margin-bottom" %>
<%= link_to "New", new_creature_path, class: "btn btn-info pull-right margin-bottom" %>

<% @creatures.each do |creature| %>
<div class="well">
  <h3><%= creature.name %></h3>
  <p><%= creature.description %></p>
  <%= link_to "", creature, method: :delete, class: 'btn btn-danger btn-sm glyphicon glyphicon-trash pull-right margin-left', data: {confirm: "Are you sure?"} %>
  <%= link_to "", edit_creature_path(creature), class: 'btn btn-primary btn-sm glyphicon glyphicon-pencil pull-right margin-left' %>
  <p><%= link_to "Permalink", creature %></p>
  <p>
  <% creature.tags.each do |tag| %>
    <%= link_to "##{tag.name}", tag %>
  <% end %>
  </p>
</div>
<% end %>

app/views/creatures/new.html.erb
<h3> ADD A NEW CREATURE </h3>

<%= bootstrap_form_for @creature do |f| %>
<%= f.text_field :name %>
<%= f.text_area :description %>
<%= f.primary %>
<%end%>

app/views/creatures/show.html.erb
<%= link_to "&larr; Back".html_safe, creatures_path, class: "btn btn-primary" %>

<h2><%= @creature.name %></h2>

<div class="well">
  <p><%= @creature.description %></p>
  <ul>
  <% @tags.each do |tag| %>
    <li><%= tag.name %></li>
  <% end %>
  </ul>
</div>

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
</head>
<body>
<h1> HOME PAGE </h1>
<%= link_to "Go to my Bog", creatures_path, class: "btn btn-primary" %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <!-- Latest compiled and minified CSS & JS -->
  <link rel="stylesheet" media="screen" href="//netdna.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <script src="//code.jquery.com/jquery.js"></script>
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  <title>Bog App</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <h1>Bog</h1>
    <div class="col-xs-12 col-sm-9 col-md-9 col-lg-9">
      <%= yield %>
    </div>
    <div class="col-xs-12 col-sm-3 col-md-3 col-lg-3">
      <h2>Links</h2>
      <ul>
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Bog", creatures_path %></li>
        <li><%= link_to "Tags", tags_path %></li>
      </ul>
    </div>
  </div>
</body>
</html>

app/views/tags/_form.html.erb
<%= bootstrap_form_for @tag do |t| %>

<%= t.text_field :name %>
<%= t.primary %>

<%end%>

app/views/tags/index.html.erb
<h1>Tags</h1>

<% @tags.each do |tag| %>


<div class="well">
  <h2>#<%= link_to tag.name, tag %></h2>


  <%= link_to 'Delete', tag, method: :delete, confirm: 'Are you sure?', class: 'btn btn-danger btn-xs glyphicon glyphicon-trash pull-right' %>
</div>


<% end %>

app/views/tags/new.html.erb
<%= link_to "&larr; Back".html_safe, tags_path, class: "btn btn-primary" %>

<h2>Create a new tag!</h2>

<%= render 'tags/form' %>

app/views/tags/show.html.erb
<h2>#<%= @tag.name %></h2>

<% @tag.creatures.each do |creature| %>
<div class="well">
  <%= link_to creature.name, creature %>
</div>
<% end %>